### ISSUE TITLE
On Device page, Instrument command doesn't work with get operation

### ISSUE THREAD

**Issue by VaibhavPawar16** [TIBCOSoftware/labs-air-ui#49]
While doing get operation on command, get request is sent with undefined command id - https://localhost:4200/edgex/localgateway/command/api/v1/device/dfbfc282-a345-494f-83e9-d559fa4c8b40/command/undefined
This may be due to fact that, command id is taken from id field of Profile/coreCommand/id field (non-existenent field) of /api/v1/device metadata service.

**Comment by magallardo** [comment]
@VaibhavPawar16 Are you trying this command on the device simulators?  Those devices don't provide get or put operations and that is the reason for the error. 
We will fix this issue and don't show the operations if not available.

**Comment by VaibhavPawar16** [comment]
@magallardo - If in the profile, those commands are listed, then by clicking on the get or put command shall get sent to device service which in turn would get sent to device. This is not happening in my case as command id is sent as undefined. I have device service which communicates with device over mqtt on receiving the commands from command service (simulated device listening on MQTT topic and responding to commands). So in my case when I do get or put operation I was expecting mqtt message to be sent to my the device. However due to command id being undefined in http call, command didn't reach device service. 
I may be wrong but by looking at code, I found that command id is being taken from  Profile/coreCommand/id field of /api/v1/device/ metadata service which is non existent field.
"coreCommands": [
                {
                    "name": "Ping",
                    "get": {
                        "path": "/api/v1/device/{deviceId}/Ping",
                        "responses": [
                            {
                                "code": "200",
                                "description": "ping the device",
                                "expectedValues": [
                                    "Ping"
                                ]
                            },
                            {
                                "code": "500",
                                "description": "internal server error"
                            }
                        ]
                    },
                    "put": {}
                },
]

**Comment by magallardo** [comment]
@VaibhavPawar16 Thanks for your feedback.  I will take a look and let you know what I find.

**Comment by torresashjian** [comment]
Closing since a lot has changed since, we will open again if problem persists
